spring:
  datasource:
    # MySQL 连接地址（数据库名 quizdb，关闭 SSL，时区 UTC）
    url: jdbc:mysql://localhost:3306/quizdb?useSSL=false&serverTimezone=UTC
    username: quizdb_user  # 数据库用户名
    password: 654321  # 数据库密码
  jpa:
    hibernate:
      ddl-auto: update  # 表结构自动更新（开发环境常用）
    show-sql: true  # 打印执行的 SQL 语句（调试用）
    properties:
        hibernate:
            format: true  # 格式化 SQL（更易读）
# 服务端口（默认 8080，冲突时可修改）
server:
  port: 8080